# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: descriptors.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='descriptors.proto',
  package='protocols',
  syntax='proto2',
  serialized_pb=_b('\n\x11\x64\x65scriptors.proto\x12\tprotocols\"\xe9\x01\n\x10\x44\x65scriptorHeader\x12\x15\n\rdescriptor_id\x18\x01 \x02(\x0c\x12\x0b\n\x03ttl\x18\x02 \x02(\x05\x12\x0c\n\x04hops\x18\x03 \x02(\x05\x12I\n\x12payload_descriptor\x18\x04 \x02(\x0e\x32-.protocols.DescriptorHeader.PayloadDescriptor\x12\x16\n\x0epayload_length\x18\x05 \x02(\x05\"@\n\x11PayloadDescriptor\x12\x08\n\x04PING\x10\x00\x12\x08\n\x04PONG\x10\x01\x12\t\n\x05QUERY\x10\x02\x12\x0c\n\x08QUERYHIT\x10\x03\">\n\x04Ping\x12\x36\n\x11\x64\x65scriptor_header\x18\x01 \x02(\x0b\x32\x1b.protocols.DescriptorHeader\"\x95\x01\n\x04Pong\x12\x36\n\x11\x64\x65scriptor_header\x18\x01 \x02(\x0b\x32\x1b.protocols.DescriptorHeader\x12\x0c\n\x04port\x18\x02 \x02(\x05\x12\x12\n\nip_address\x18\x03 \x02(\x0c\x12\x1a\n\x12no_of_files_shared\x18\x04 \x02(\x05\x12\x17\n\x0fno_of_kb_shared\x18\x05 \x02(\x05\"o\n\x05Query\x12\x36\n\x11\x64\x65scriptor_header\x18\x01 \x02(\x0b\x32\x1b.protocols.DescriptorHeader\x12\x15\n\rminimum_speed\x18\x02 \x02(\x05\x12\x17\n\x0fsearch_criteria\x18\x03 \x02(\x0c\"\x9d\x02\n\x08QueryHit\x12\x36\n\x11\x64\x65scriptor_header\x18\x01 \x02(\x0b\x32\x1b.protocols.DescriptorHeader\x12\x12\n\nno_of_hits\x18\x02 \x02(\x05\x12\x0c\n\x04port\x18\x03 \x02(\x05\x12\x12\n\nip_address\x18\x04 \x02(\x0c\x12\r\n\x05speed\x18\x05 \x02(\x05\x12\x31\n\nresult_set\x18\x06 \x03(\x0b\x32\x1d.protocols.QueryHit.ResultSet\x12\x1a\n\x12servent_identifier\x18\x07 \x02(\x0c\x1a\x45\n\tResultSet\x12\x12\n\nfile_index\x18\x01 \x02(\x05\x12\x11\n\tfile_size\x18\x02 \x02(\x05\x12\x11\n\tfile_name\x18\x03 \x02(\x0c')
)



_DESCRIPTORHEADER_PAYLOADDESCRIPTOR = _descriptor.EnumDescriptor(
  name='PayloadDescriptor',
  full_name='protocols.DescriptorHeader.PayloadDescriptor',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PONG', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUERY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUERYHIT', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=202,
  serialized_end=266,
)
_sym_db.RegisterEnumDescriptor(_DESCRIPTORHEADER_PAYLOADDESCRIPTOR)


_DESCRIPTORHEADER = _descriptor.Descriptor(
  name='DescriptorHeader',
  full_name='protocols.DescriptorHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='descriptor_id', full_name='protocols.DescriptorHeader.descriptor_id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ttl', full_name='protocols.DescriptorHeader.ttl', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hops', full_name='protocols.DescriptorHeader.hops', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload_descriptor', full_name='protocols.DescriptorHeader.payload_descriptor', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload_length', full_name='protocols.DescriptorHeader.payload_length', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DESCRIPTORHEADER_PAYLOADDESCRIPTOR,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=266,
)


_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='protocols.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='descriptor_header', full_name='protocols.Ping.descriptor_header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=330,
)


_PONG = _descriptor.Descriptor(
  name='Pong',
  full_name='protocols.Pong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='descriptor_header', full_name='protocols.Pong.descriptor_header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='protocols.Pong.port', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip_address', full_name='protocols.Pong.ip_address', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='no_of_files_shared', full_name='protocols.Pong.no_of_files_shared', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='no_of_kb_shared', full_name='protocols.Pong.no_of_kb_shared', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=482,
)


_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='protocols.Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='descriptor_header', full_name='protocols.Query.descriptor_header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minimum_speed', full_name='protocols.Query.minimum_speed', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='search_criteria', full_name='protocols.Query.search_criteria', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=595,
)


_QUERYHIT_RESULTSET = _descriptor.Descriptor(
  name='ResultSet',
  full_name='protocols.QueryHit.ResultSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_index', full_name='protocols.QueryHit.ResultSet.file_index', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_size', full_name='protocols.QueryHit.ResultSet.file_size', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='protocols.QueryHit.ResultSet.file_name', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=814,
  serialized_end=883,
)

_QUERYHIT = _descriptor.Descriptor(
  name='QueryHit',
  full_name='protocols.QueryHit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='descriptor_header', full_name='protocols.QueryHit.descriptor_header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='no_of_hits', full_name='protocols.QueryHit.no_of_hits', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='protocols.QueryHit.port', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip_address', full_name='protocols.QueryHit.ip_address', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='protocols.QueryHit.speed', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result_set', full_name='protocols.QueryHit.result_set', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='servent_identifier', full_name='protocols.QueryHit.servent_identifier', index=6,
      number=7, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_QUERYHIT_RESULTSET, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=598,
  serialized_end=883,
)

_DESCRIPTORHEADER.fields_by_name['payload_descriptor'].enum_type = _DESCRIPTORHEADER_PAYLOADDESCRIPTOR
_DESCRIPTORHEADER_PAYLOADDESCRIPTOR.containing_type = _DESCRIPTORHEADER
_PING.fields_by_name['descriptor_header'].message_type = _DESCRIPTORHEADER
_PONG.fields_by_name['descriptor_header'].message_type = _DESCRIPTORHEADER
_QUERY.fields_by_name['descriptor_header'].message_type = _DESCRIPTORHEADER
_QUERYHIT_RESULTSET.containing_type = _QUERYHIT
_QUERYHIT.fields_by_name['descriptor_header'].message_type = _DESCRIPTORHEADER
_QUERYHIT.fields_by_name['result_set'].message_type = _QUERYHIT_RESULTSET
DESCRIPTOR.message_types_by_name['DescriptorHeader'] = _DESCRIPTORHEADER
DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['Pong'] = _PONG
DESCRIPTOR.message_types_by_name['Query'] = _QUERY
DESCRIPTOR.message_types_by_name['QueryHit'] = _QUERYHIT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DescriptorHeader = _reflection.GeneratedProtocolMessageType('DescriptorHeader', (_message.Message,), dict(
  DESCRIPTOR = _DESCRIPTORHEADER,
  __module__ = 'descriptors_pb2'
  # @@protoc_insertion_point(class_scope:protocols.DescriptorHeader)
  ))
_sym_db.RegisterMessage(DescriptorHeader)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), dict(
  DESCRIPTOR = _PING,
  __module__ = 'descriptors_pb2'
  # @@protoc_insertion_point(class_scope:protocols.Ping)
  ))
_sym_db.RegisterMessage(Ping)

Pong = _reflection.GeneratedProtocolMessageType('Pong', (_message.Message,), dict(
  DESCRIPTOR = _PONG,
  __module__ = 'descriptors_pb2'
  # @@protoc_insertion_point(class_scope:protocols.Pong)
  ))
_sym_db.RegisterMessage(Pong)

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), dict(
  DESCRIPTOR = _QUERY,
  __module__ = 'descriptors_pb2'
  # @@protoc_insertion_point(class_scope:protocols.Query)
  ))
_sym_db.RegisterMessage(Query)

QueryHit = _reflection.GeneratedProtocolMessageType('QueryHit', (_message.Message,), dict(

  ResultSet = _reflection.GeneratedProtocolMessageType('ResultSet', (_message.Message,), dict(
    DESCRIPTOR = _QUERYHIT_RESULTSET,
    __module__ = 'descriptors_pb2'
    # @@protoc_insertion_point(class_scope:protocols.QueryHit.ResultSet)
    ))
  ,
  DESCRIPTOR = _QUERYHIT,
  __module__ = 'descriptors_pb2'
  # @@protoc_insertion_point(class_scope:protocols.QueryHit)
  ))
_sym_db.RegisterMessage(QueryHit)
_sym_db.RegisterMessage(QueryHit.ResultSet)


# @@protoc_insertion_point(module_scope)
